version: "3.9"
services:
  base_no_env:
    &base_no_env
    image: "robdmc/local_metabase:latest"
    links:
      - db
    volumes:
      - ./code:/code
      - env:/env
    working_dir: /code

  base:
    &base
    <<: *base_no_env
    env_file: variables.env

  shell:
    <<: *base
    command: /bin/bash

  test:
    <<: *base_no_env
    command: /bin/bash

  build_env:
    <<: *base_no_env
    entrypoint: /code/build_env.sh

  make_db:
    <<: *base
    entrypoint: /code/make_db.sh

  pgcli:
    <<: *base
    entrypoint: /code/run_pgcli.py

  truncate:
    <<: *base
    entrypoint: /code/truncate.py

  notebook:
    <<: *base
    ports:
      - "9999:9999"
    command: jupyter-lab  --port=9999  --NotebookApp.iopub_data_rate_limit=10000000000 --allow-root --no-browser --ip=0.0.0.0

  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
  env:
    driver: local
